name: Update blog posts

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  update-readme-with-latest-posts:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Fetching RSS feed
      run: wget --quiet -O rss.xml https://atabakoff.com/posts/index.xml
    - name: Parsing the feed
      run: ../daydiff/daydiff/rss.sh rss.xml > posts.html
    - name: Updating the README.md
      run:  POSTS=$( cat posts.html ) && sed -E "s#<\!--blog:posts>(.*)<\/blog:posts-->#$POSTS#" README.md > README.tmp && mv README.tmp README.md
    - name: Cleanup
      run: rm README.tmp rss.xml posts.html
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated latest blog posts
