name: Update blog posts

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update-readme-with-latest-posts:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Fetching RSS feed
      run: wget --quiet -O rss.xml https://atabakoff.com/posts/index.xml
    - name: Debug
      run: |
        ls -la /home/runner/work/daydiff/daydiff
        pwd
        ls -la `pwd`
        ls -la ~
    - name: Parsing the feed
      run: $( pwd )/rss.sh rss.xml > posts.html
    - name: Updating the README.md
      run:  |
        POSTS=$( cat posts.html )
        sed -E "s#<\!--blog:start>(.*)<\/blog:end-->#<\!--blog:start>$POSTS<\/blog:end-->#" README.md > README.tmp
        mv README.tmp README.md
    - name: Cleanup
      run: rm -f rss.xml posts.html
    - name: Push changes
      run: |
        git config --global user.name 'Aleksandr Tabakov'
        git config --global user.email 'daydiff@users.noreply.github.com'
        git commit -am "Updated blog posts"
        git push
